### ISSUE TITLE
Add qr code generation

### ISSUE THREAD

**Issue by bencinn** [ItsPungpond98/School-Parking-Project#13]
We could use this https://kit.svelte.dev/docs/building-your-app#during-the-build thingie that basically run at build time and generate qr code file and then serve them at runtime? like /qrcode/{1,2,3,4,5,...}
It could be like this
```Typescript
import {t} from "whereever/the/parking/lot/data/exist"

const generateqrcode = () => {
    // https://davidshimjs.github.io/qrcodejs/ ?
}

for (int i  = 0; i < t.length(); i++) {
   generateqrcode(t[i])
}
```

**Comment by ItsPungpond98** [comment]
So, currently, the parking lot array is just info about parked spots. So, I think we should utilize the max space info from the `slotconfig.ts` instead. Although it may not be consistant, it might be the best way to get the amount of parking lot for now.

**Comment by bencinn** [comment]
> So, currently, the parking lot array is just info about parked spots. So, I think we should utilize the max space info from the `slotconfig.ts` instead. Although it may not be consistant, it might be the best way to get the amount of parking lot for now.

I don't think we need consistency when it's in build time? Correct me please if I say something stupid.

**Comment by ItsPungpond98** [comment]
Check discord ( ｡ •̀ ᴖ •́ ｡)💢
