### ISSUE TITLE
Fix format time script

### ISSUE THREAD

**Issue by bencinn** [ItsPungpond98/School-Parking-Project#15]
I think the timezone is supposed to be"Asia/Bangkok" instead of "Asia/Jakarta"?

**Comment by ItsPungpond98** [comment]
Bruh, Bangkok and Jakarta uses same timezone lmao. They both have no DST.

**Comment by bencinn** [comment]
Idk when I see Jakarta in the code it feels like I'm reading with some frogs on my left of the PC or smth. Just feels weird. Please change it. It just aaaaaaa

**Comment by bencinn** [comment]
also seems more readable idk. maybe im stupid
